# *
# * This Source Code Form is subject to the terms of the Mozilla Public
# * License, v. 2.0. If a copy of the MPL was not distributed with this
# * file, You can obtain one at http://mozilla.org/MPL/2.0/.
# *
version: "3.8"
services:
  # Database service. It's PostgreSQL, see the Dockerfile in ./database
  database:
    build: ./containers/database/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=pleaseChange # default postgres password that should be changed for security.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    # Uncomment the below to access PostgreSQL server from the host machine
    ports:
      - "5432:5432"

  # Web service runs Node
  web:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 15s
      timeout: 1s
      retries: 6
    environment:
      - OED_PRODUCTION=no
      - OED_SERVER_PORT=3000
      - OED_DB_USER=oed
      - OED_DB_DATABASE=oed
      - OED_DB_TEST_DATABASE=oed_testing
      - OED_DB_PASSWORD=opened
      - OED_DB_HOST=database # Docker will set this hostname
      - OED_DB_PORT=5432
      - OED_TOKEN_SECRET=?
      - OED_LOG_FILE=log.txt
      - OED_MAIL_METHOD=none
      - OED_MAIL_SMTP=smtp.example.com
      - OED_MAIL_SMTP_PORT=465
      - OED_MAIL_IDENT=someone@example.com
      - OED_MAIL_CREDENTIAL=credential
      - OED_MAIL_FROM=mydomain@example.com
      - OED_MAIL_TO=someone@example.com
      - OED_MAIL_ORG=My Organization Name
      - TZ=Etc/UTC
    build:
      context: ./
      dockerfile: ./containers/web/Dockerfile
    links:
      - database
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    depends_on:
      - database
    command:
      [
        "bash",
        "./src/scripts/installOED.sh",
        "${install_args:-}"
      ]

  # Cypress testing service
  cypress:
    image: cypress/included
    profiles:
      - ui-testing
    environment:
      - CYPRESS_BASE_URL=http://web:3000
      - DISPLAY=:99
    working_dir: /usr/src/app
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
    entrypoint: >
      /bin/sh -c "
      rm -f /tmp/.X99-lock &&
      Xvfb :99 -screen 0 1024x768x16"
